<a href="https://colab.research.google.com/github/sedwna/pytorch-learn/blob/main/main_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import torch

In [ ]:
torch.__version__

'2.5.1+cu124'

In [ ]:
# create a Scalar
torch.tensor(4) # tensor with 0D

tensor(4)

In [ ]:
#create a vector
torch.tensor([1,2,3,4]) # tensor with 1D

tensor([1, 2, 3, 4])

In [ ]:
# create a matrix
torch.tensor([[1,2,3], # tensor with 2D
              [4,5,6],
              [7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# create a column vector
torch.tensor([[1], # tensor with 2D
              [2],
              [3]])

tensor([[1],
        [2],
        [3]])

In [ ]:
# create a N-D tensor
torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [ ]:
# dtype
a = torch.tensor([1,2,3,4],dtype=torch.uint8) #uint8 = 8bit integer(unsigned) 0 - 255
# defult torc.uint64 or torch.float32

In [ ]:
# convert type
a = a.type(torch.float16) #or a = a.float()
a


tensor([1., 2., 3., 4.], dtype=torch.float16)

In [ ]:
# device
# how a tensor Run in GPU or CPU

a = torch.tensor([1,2,3,4],dtype=torch.uint8,device='cpu')
print(a.device) # a method for check a tensor run in wich mode(gpu or cpu)

# a = torch.tensor([1,2,3,4],dtype=torch.uint8,device='cuda')
print(a.device)

a = a.cpu() #or a = a.gpu() #switch from gpu to cpu or reverse


cpu
cpu


In [ ]:
scalar = torch.tensor(1)

vector = torch.tensor([1,2,3,4])

matrix = torch.tensor([[1,2],
                       [1,2],
                       [1,3]])

tensor = torch.tensor([[[1,2,3],
                        [1,2,3]],
                                [[1,2,3],
                                 [1,0,3]],
                                        [[1,2,3],
                                         [1,2,7]]])

In [ ]:
scalar.shape, vector.shape, matrix.shape, tensor.shape

(torch.Size([]), torch.Size([4]), torch.Size([2, 2]), torch.Size([3, 2, 3]))

In [ ]:
c, r, cc = tensor.shape
c, r, cc

(3, 2, 3)

In [ ]:
tensor.size() , tensor.size(0)

(torch.Size([3, 2, 3]), 3)

In [ ]:
tensor.min(), tensor.max()

(tensor(0), tensor(7))

In [ ]:
# we cant get a mean for int64
tensor.float().mean() ,tensor.float().std()

(tensor(2.1111), tensor(1.5297))

In [ ]:
# transpose = rotate 90 degree right
matrix.t()

tensor([[1, 1, 1],
        [2, 2, 3]])

In [36]:
# Difference with _ and empty
scalar = torch.tensor(-1)

print(scalar.abs())
print(scalar)

print(scalar.abs_())
print(scalar)

tensor(1)
tensor(-1)
tensor(1)
tensor(1)
