<a href="https://colab.research.google.com/github/sedwna/pytorch-learn/blob/main/src/main_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import torch

In [3]:
torch.__version__

'2.5.1+cu124'

In [4]:
# create a Scaler
torch.tensor(4) # tensor with 0D

tensor(4)

In [7]:
#create a vector
torch.tensor([1,2,3,4]) # tensor with 1D

tensor([1, 2, 3, 4])

In [9]:
# create a matrix
torch.tensor([[1,2,3], # tensor with 2D
              [4,5,6],
              [7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
# create a column vector
torch.tensor([[1], # tensor with 2D
              [2],
              [3]])

tensor([[1],
        [2],
        [3]])

In [11]:
# create a N-D tensor
torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [9]:
# dtype
a = torch.tensor([1,2,3,4],dtype=torch.uint8) #uint8 = 8bit integer(unsigned) 0 - 255
# defult torc.uint64 or torch.float32

In [10]:
# convert type
a = a.type(torch.float16) #or a = a.float()
a


tensor([1., 2., 3., 4.], dtype=torch.float16)

In [13]:
# device
# how a tensor Run in GPU or CPU

a = torch.tensor([1,2,3,4],dtype=torch.uint8,device='cpu')
print(a.device) # a method for check a tensor run in wich mode(gpu or cpu)

a = torch.tensor([1,2,3,4],dtype=torch.uint8,device='cuda')
print(a.device)

a = a.cpu() #or a = a.gpu() #switch from gpu to cpu or reverse


cpu
cuda:0


tensor([1, 2, 3, 4], dtype=torch.uint8)